### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by hannesa2** [PatilShreyas/DataStoreExample#2]
Just for your info, this sample doesn't build anymore with

<img width="629" alt="image" src="https://user-images.githubusercontent.com/3314607/107870316-62b3ce00-6e97-11eb-93cd-481329cba48f.png">

and run into

<img width="569" alt="image" src="https://user-images.githubusercontent.com/3314607/107870325-79f2bb80-6e97-11eb-853c-cc974c5e2b97.png">

**Comment by hannesa2** [comment]
This seems to be the solution

<img width="581" alt="image" src="https://user-images.githubusercontent.com/3314607/107870470-defae100-6e98-11eb-9113-f65c6e643fa2.png">

<img width="702" alt="image" src="https://user-images.githubusercontent.com/3314607/107870479-eb7f3980-6e98-11eb-8341-f5e69755a8bf.png">

**Comment by PatilShreyas** [comment]
@hannesa2 would you like to work on it?

**Comment by hannesa2** [comment]
Sorry, I'm too lazy to fork and make a pull request.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/3314607/107871981-e1643780-6ea6-11eb-904a-fd2204ace34f.png">

The only think I can offer is to push direct to your master, if I've the right.

Independent of this, I don't know to handle this (yet)

<img width="370" alt="image" src="https://user-images.githubusercontent.com/3314607/107871988-0062c980-6ea7-11eb-9749-95a4ba95f9c9.png">

**Comment by PatilShreyas** [comment]
You'll need to raise PR for this change. So that it would be easy to review changes
